Fix a number of typos that break the framing functionality.
The `max_x` and `max_y` were inadvertently swapped, producing wrong
results.

Also, when the user tried to frame only the alternate mesh, an exception
was produced:

```
Traceback (most recent call last):
  File "mkdd_editor.py", line 753, in <lambda>
    lambda _checked: self.frame_selection(adjust_zoom=True))
  File "mkdd_editor.py", line 382, in frame_selection
    minx, miny, minz, maxx, maxy, maxz = self.compute_objects_extent(selected_only)
  File "mkdd_editor.py", line 503, in compute_objects_extent
    extend.extend([min_x, min_y, min_z, max_y, max_x, max_z])
AttributeError: 'function' object has no attribute 'extend'
```

`extend` was used where `extent` was expected.