Added checks before accessing config keys while restoring geometry.
This fixes a regression introduced as part of https://github.com/RenolY2/mkdd-track-editor/commit/2667774fb676e692bc8dcabba0be5208989b0026.

Reproduction steps:

- Launch the editor from a fresh installation (or erase the
  `editor_config.ini` file).
- Close the editor without any interaction.
- Launch the editor again. A *fatal* exception is produced:
```
Traceback (most recent call last):
  File "mkdd_editor.py", line 2290, in <module>
    editor_gui = GenEditor()
  File "mkdd_editor.py", line 133, in __init__
    self.restore_geometry()
  File "mkdd_editor.py", line 162, in restore_geometry
    self.restoreGeometry(to_byte_array(geo_config["window_geometry"]))
  File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'window_geometry'
```